//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyTestSven
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataTable
    {
        public int DataId { get; set; }
        public int QuestionId { get; set; }
        public string AnsvarInt { get; set; }
        public string AnsvarString { get; set; }
    
        public virtual QuestionTabel QuestionTabel { get; set; }
    }
}
