//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyTestSven
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurveyEntities1 : DbContext
    {
        public SurveyEntities1()
            : base("name=SurveyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataTable> DataTable { get; set; }
        public virtual DbSet<ProfileTabel> ProfileTabel { get; set; }
        public virtual DbSet<QuestionTabel> QuestionTabel { get; set; }
        public virtual DbSet<SurveyTabel> SurveyTabel { get; set; }
    }
}
