//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyTestSven
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileTabel
    {
        public ProfileTabel()
        {
            this.SurveyTabel = new HashSet<SurveyTabel>();
        }
    
        public int ProfileId { get; set; }
        public string Navn { get; set; }
        public string Butik { get; set; }
        public string Adresse { get; set; }
    
        public virtual ICollection<SurveyTabel> SurveyTabel { get; set; }
    }
}
