//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyTestSven
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionTabel
    {
        public QuestionTabel()
        {
            this.DataTable = new HashSet<DataTable>();
        }
    
        public int QuestionId { get; set; }
        public int SurveyId { get; set; }
        public string Question { get; set; }
        public string Ansvar1 { get; set; }
        public string Ansvar2 { get; set; }
        public string Ansvar3 { get; set; }
        public string Ansvar4 { get; set; }
        public string Ansvar5 { get; set; }
        public string Ansvar6 { get; set; }
        public Nullable<int> Ansvar7 { get; set; }
        public string AnsvarString { get; set; }
        public string Correct { get; set; }
    
        public virtual ICollection<DataTable> DataTable { get; set; }
        public virtual SurveyTabel SurveyTabel { get; set; }
    }
}
