//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyTestSven
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyTabel
    {
        public SurveyTabel()
        {
            this.QuestionTabel = new HashSet<QuestionTabel>();
        }
    
        public int SurveyId { get; set; }
        public int ProfileId { get; set; }
        public string SurveyNavn { get; set; }
    
        public virtual ProfileTabel ProfileTabel { get; set; }
        public virtual ICollection<QuestionTabel> QuestionTabel { get; set; }
    }
}
